### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Shardcached/shardcached#4]
I would like to point out that identifiers like "[`__SHCD_ACL_H__`](https://github.com/Shardcached/shardcached/blob/475616f0bac639bf53af44d040351fb42b02d865/src/acl.h#L1)" and "[`__exit`](https://github.com/Shardcached/shardcached/blob/1c9d65654f0705d39c44e125d005e2d97edf2c93/src/shardcached.c#L944)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by xant** [comment]
d5bafdba030290b7f103451c3eb329475ebb705d

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Shardcached/shardcached/commit/d5bafdba030290b7f103451c3eb329475ebb705d "Deletion of a few underscores").
