### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Shardcached/shardcached#5]
Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [shcd_storage_init](https://github.com/Shardcached/shardcached/blob/e7692de4472e21f8b9d58c138800f6f068a3c9cb/src/storage.c#L19)
- [fwrite](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fwrite.html "Binary output") ⇒ [main](https://github.com/Shardcached/shardcached/blob/1c9d65654f0705d39c44e125d005e2d97edf2c93/src/shardcached.c#L969)

**Comment by xant** [comment]
allocations are not going to be checked here ... maybe it could make sense to just configure malloc to make it directly call abort() on fail (I think it's a configurable flag)

failure in storing the pid into the pidfile is now properly handled : 86d51d9df9f2c852f150adcd5a924bd7fdc13b08

**Comment by elfring** [comment]
This issue is not completely fixed so far. How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for this software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](http://aspectc.net/ac_tutorial.html#reusablemachecking "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by xant** [comment]
I don't think such considerations are relevant here ... so no actions will be taken on such matter

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

**Comment by xant** [comment]
I suggest you to get a life ;)

nothing more is going to be done here!
