### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [Shardcached/shardcached#6]
I guess that a different program design will be needed for your function "[shardcached_stop](https://github.com/Shardcached/shardcached/blob/1c9d65654f0705d39c44e125d005e2d97edf2c93/src/shardcached.c#L235 "Check signal handling implementation")".
* [The variable "should_exit"](https://github.com/Shardcached/shardcached/blob/1c9d65654f0705d39c44e125d005e2d97edf2c93/src/shardcached.c#L66 "Update candidate") should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.").
* [The function "pthread_mutex_lock"](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "Lock a mutex.") does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").

**Comment by xant** [comment]
947d4cc3468e61302491914195daf823e78fc4a5

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Shardcached/shardcached/commit/947d4cc3468e61302491914195daf823e78fc4a5 "Safer signal handling").
